import type { Metadata } from "next";
import Header from "@/component/Header";
import Footer from "@/component/Footer";

import "./css/global.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className="page-wrapper">
          <main>
            {children}
          </main>
        </div>
        <Footer />
      </body>
    </html>
  );
}
