// ── helpers ───────────────────────────────────────────────────

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function toPascalCase(s: string): string {
  return s
    .replace(/[-_\s]+(.)/g, (_, c) => c.toUpperCase())
    .replace(/^(.)/, (_, c) => c.toUpperCase());
}

function toCamelCase(s: string): string {
  const p = toPascalCase(s);
  return p.charAt(0).toLowerCase() + p.slice(1);
}

// ── type inference ────────────────────────────────────────────

type PrismaFieldType =
  | "String"
  | "Int"
  | "Float"
  | "Boolean"
  | "DateTime"
  | string; // model name for relations

interface PrismaField {
  name: string;
  type: PrismaFieldType;
  isArray: boolean;
  isOptional: boolean;
  decorators: string[];
}

interface PrismaModel {
  name: string;
  fields: PrismaField[];
}

function inferScalarType(val: unknown): PrismaFieldType | null {
  if (val === null || val === undefined) return null;
  if (typeof val === "boolean") return "Boolean";
  if (typeof val === "number") return Number.isInteger(val) ? "Int" : "Float";
  if (typeof val === "string") {
    // ISO date heuristic
    if (/^\d{4}-\d{2}-\d{2}(T[\d:.Z+-]+)?$/.test(val)) return "DateTime";
    return "String";
  }
  return null;
}

// ── JSON → Prisma ─────────────────────────────────────────────

export function jsonToPrisma(json: unknown): string {
  const models: Map<string, PrismaModel> = new Map();

  function processObject(
    obj: Record<string, unknown>,
    modelName: string
  ): void {
    if (models.has(modelName)) return;

    const fields: PrismaField[] = [];

    // Always add id field first
    fields.push({
      name: "id",
      type: "Int",
      isArray: false,
      isOptional: false,
      decorators: ["@id", "@default(autoincrement())"],
    });

    for (const [rawKey, val] of Object.entries(obj)) {
      const name = toCamelCase(rawKey);

      // Array field
      if (Array.isArray(val)) {
        const first = val[0];
        if (first === undefined || first === null) {
          fields.push({ name, type: "String", isArray: true, isOptional: false, decorators: [] });
        } else if (typeof first === "object" && first !== null) {
          const relModel = toPascalCase(rawKey.replace(/s$/, ""));
          processObject(first as Record<string, unknown>, relModel);
          fields.push({ name, type: relModel, isArray: true, isOptional: false, decorators: [] });
        } else {
          const t = inferScalarType(first) ?? "String";
          fields.push({ name, type: t, isArray: true, isOptional: false, decorators: [] });
        }
        continue;
      }

      // Nested object → relation
      if (val !== null && typeof val === "object") {
        const relModel = toPascalCase(rawKey);
        processObject(val as Record<string, unknown>, relModel);
        fields.push({
          name,
          type: relModel,
          isArray: false,
          isOptional: true,
          decorators: [],
        });
        continue;
      }

      // Null → optional String
      if (val === null) {
        fields.push({ name, type: "String", isArray: false, isOptional: true, decorators: [] });
        continue;
      }

      // Scalar
      const type = inferScalarType(val) ?? "String";
      const decorators: string[] = [];

      // Heuristics for common field names
      if (name === "email") decorators.push("@unique");
      if (name === "createdAt" || name === "updatedAt") {
        decorators.push(name === "createdAt" ? "@default(now())" : "@updatedAt");
      }

      fields.push({ name, type, isArray: false, isOptional: false, decorators });
    }

    models.set(modelName, { name: modelName, fields });
  }

  // Normalize root input
  const root = Array.isArray(json) ? json[0] : json;
  if (typeof root !== "object" || root === null) {
    throw new Error("Input must be a JSON object or array of objects.");
  }

  // Detect top-level model name(s)
  const rootObj = root as Record<string, unknown>;
  const firstVal = Object.values(rootObj)[0];

  if (
    typeof firstVal === "object" &&
    firstVal !== null &&
    !Array.isArray(firstVal) &&
    Object.keys(rootObj).every(
      (k) =>
        typeof rootObj[k] === "object" &&
        rootObj[k] !== null &&
        !Array.isArray(rootObj[k])
    )
  ) {
    // Top-level keys are model names
    for (const [modelName, modelData] of Object.entries(rootObj)) {
      processObject(modelData as Record<string, unknown>, toPascalCase(modelName));
    }
  } else {
    // Single model, guess name as "Model"
    processObject(rootObj, "Model");
  }

  // Render models
  const lines: string[] = [
    '// Generated by json-to-prisma converter',
    '// Review and adjust field types, relations, and decorators as needed.',
    '',
    'generator client {',
    '  provider = "prisma-client-js"',
    '}',
    '',
    'datasource db {',
    '  provider = "postgresql"',
    '  url      = env("DATABASE_URL")',
    '}',
    '',
  ];

  for (const model of models.values()) {
    lines.push(`model ${model.name} {`);

    // Calculate column widths for alignment
    const nameWidth = Math.max(...model.fields.map((f) => f.name.length)) + 1;
    const typeWidth = Math.max(
      ...model.fields.map((f) => {
        const t = f.type + (f.isArray ? "[]" : "") + (f.isOptional ? "?" : "");
        return t.length;
      })
    ) + 1;

    for (const field of model.fields) {
      const typeStr = field.type + (f => f.isArray ? "[]" : f.isOptional ? "?" : "")(field);
      const namePad = field.name.padEnd(nameWidth);
      const typePad = typeStr.padEnd(typeWidth);
      const decs = field.decorators.length ? " " + field.decorators.join(" ") : "";
      lines.push(`  ${namePad}${typePad}${decs}`.trimEnd());
    }

    lines.push("}");
    lines.push("");
  }

  return lines.join("\n").trimEnd();
}

// ── Prisma → JSON ─────────────────────────────────────────────

const PRISMA_SCALAR_DEFAULTS: Record<string, unknown> = {
  String: "",
  Int: 0,
  Float: 0.0,
  Boolean: false,
  DateTime: new Date().toISOString(),
  Json: {},
  Bytes: "",
  Decimal: 0,
  BigInt: 0,
};

export function prismaToJson(schema: string): Record<string, unknown> {
  const result: Record<string, unknown> = {};

  // Extract all model blocks
  const modelRegex = /model\s+(\w+)\s*\{([^}]+)\}/g;
  let modelMatch: RegExpExecArray | null;

  const modelDefs: Map<string, Array<{ name: string; type: string; isArray: boolean; isOptional: boolean }>> = new Map();

  while ((modelMatch = modelRegex.exec(schema)) !== null) {
    const modelName = modelMatch[1];
    const body = modelMatch[2];
    const fields: Array<{ name: string; type: string; isArray: boolean; isOptional: boolean }> = [];

    const lines = body.split("\n").map((l) => l.trim()).filter(Boolean);

    for (const line of lines) {
      // Skip comments
      if (line.startsWith("//") || line.startsWith("@@") || line.startsWith("@")) continue;

      const parts = line.split(/\s+/);
      if (parts.length < 2) continue;

      const fieldName = parts[0];
      let fieldType = parts[1];

      const isArray = fieldType.endsWith("[]");
      const isOptional = fieldType.endsWith("?");
      fieldType = fieldType.replace(/[\[\]?]/g, "");

      fields.push({ name: fieldName, type: fieldType, isArray, isOptional });
    }

    modelDefs.set(modelName, fields);
  }

  if (modelDefs.size === 0) {
    throw new Error('No model blocks found. Make sure your schema contains at least one "model ModelName { ... }" block.');
  }

  // Resolve model to JSON sample object
  function resolveModel(
    modelName: string,
    visited: Set<string> = new Set()
  ): Record<string, unknown> {
    if (visited.has(modelName)) return { id: 0 }; // break circular
    visited.add(modelName);

    const fields = modelDefs.get(modelName);
    if (!fields) return {};

    const obj: Record<string, unknown> = {};

    for (const field of fields) {
      // Skip relation scalar foreign keys convention (e.g. userId Int)
      if (field.name === "id") { obj[field.name] = 0; continue; }

      const scalar = PRISMA_SCALAR_DEFAULTS[field.type];

      let val: unknown;
      if (scalar !== undefined) {
        val = field.type === "String" ? field.name : scalar;
      } else if (modelDefs.has(field.type)) {
        val = resolveModel(field.type, new Set(visited));
      } else {
        val = null;
      }

      if (field.isArray) {
        val = val !== null ? [val] : [];
      } else if (field.isOptional) {
        val = val ?? null;
      }

      obj[field.name] = val;
    }

    return obj;
  }

  for (const [modelName] of modelDefs) {
    result[modelName] = resolveModel(modelName);
  }

  // If only one model, return it directly
  if (modelDefs.size === 1) {
    return result[Array.from(modelDefs.keys())[0]] as Record<string, unknown>;
  }

  return result;
}